# Generated by Django 5.2.4 on 2025-07-18 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='extracted_skills',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
