# Generated by Django 5.2.4 on 2025-07-19 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_extracted_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='resume_template_choice',
            field=models.IntegerField(choices=[(1, 'Professional'), (2, 'Creative'), (3, 'Minimalistic')], default=1),
        ),
    ]
