# Generated by Django 5.2.4 on 2026-02-09 10:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_userprofile_resume_template_choice'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'Logged In'), ('resume_generated', 'Resume Generated'), ('test_completed', 'Competency Test Completed'), ('roadmap_created', 'Roadmap Created'), ('skills_extracted', 'Skills Extracted'), ('job_search', 'Job Search Performed'), ('profile_updated', 'Profile Updated'), ('interview_prep', 'Interview Prep Started')], max_length=30)),
                ('detail', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
