# Generated by Django 5.2.4 on 2025-07-18 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_builder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
