# Generated by Django 5.2.12 on 2026-03-21 07:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("competency", "0005_interviewquestion"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="feedback",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="answer",
            name="gaps",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="answer",
            name="model_answer",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="answer",
            name="score",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="answer",
            name="skill_tags",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="answer",
            name="strengths",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="competencytestsession",
            name="company_type",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="competencytestsession",
            name="seniority",
            field=models.CharField(
                choices=[
                    ("junior", "Junior"),
                    ("mid", "Mid-Level"),
                    ("senior", "Senior"),
                    ("staff", "Staff/Lead"),
                ],
                default="mid",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="interviewquestion",
            name="confidence",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="interviewquestion",
            name="time_taken",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="InterviewSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_role", models.CharField(max_length=100)),
                ("category", models.CharField(default="technical", max_length=20)),
                (
                    "mode",
                    models.CharField(
                        choices=[("practice", "Practice"), ("simulator", "Simulator")],
                        default="practice",
                        max_length=20,
                    ),
                ),
                ("overall_score", models.FloatField(blank=True, null=True)),
                ("hire_decision", models.CharField(blank=True, max_length=20)),
                ("confidence_scores", models.JSONField(blank=True, default=list)),
                ("completed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interview_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="interviewquestion",
            name="session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="questions",
                to="competency.interviewsession",
            ),
        ),
    ]
