# Generated by Django 5.2.4 on 2026-03-21 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competency', '0006_question_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='competencytestsession',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=20),
        ),
    ]
