# Generated by Django 5.2.12 on 2026-03-22 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mock_interview", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="interviewsession",
            name="prep_mode",
            field=models.CharField(choices=[("subjective", "Subjective"), ("interactive", "Interactive")], default="subjective", max_length=20),
        ),
        migrations.AddField(
            model_name="interviewsession",
            name="target_role",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="interviewsession",
            name="target_company",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="interviewsession",
            name="tech_stack",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="interviewsession",
            name="current_profile",
            field=models.TextField(blank=True, null=True),
        ),
    ]
