# Generated by Django 5.2.12 on 2026-03-22 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mock_interview', '0002_interviewsession_profile_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewsession',
            name='body_language_metrics',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
