# Generated by Django 5.2.4 on 2026-02-09 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0005_rename_recommended_courses_learningpath_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skillgapanalysis',
            name='steps',
        ),
        migrations.AlterField(
            model_name='skillgapanalysis',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
